2021-05-16 10:46:51 - ERROR - assertion error, wrong input by admin
Traceback (most recent call last):
  File "D:\Maktab\week_7\final_project\New folder\main_menue.py", line 122, in <module>
    event.Event.display_event('file_event_csv')
  File "D:\Maktab\week_7\final_project\New folder\event.py", line 293, in display_event
    my_logger_event.inf('evnt are displayed sucessfully', exc_info=True)
AttributeError: 'Logger' object has no attribute 'inf'
2021-05-16 10:47:38 - INFO - creat event by admin
NoneType: None
2021-05-16 10:47:40 - ERROR - assertion error, wrong input by admin
Traceback (most recent call last):
  File "D:\Maktab\week_7\final_project\New folder\main_menue.py", line 122, in <module>
    event.Event.display_event('file_event_csv')
  File "D:\Maktab\week_7\final_project\New folder\event.py", line 293, in display_event
    my_logger_event.inf('evnt are displayed sucessfully', exc_info=True)
AttributeError: 'Logger' object has no attribute 'inf'
2021-05-16 10:47:58 - INFO - change password for admin
NoneType: None
2021-05-16 10:48:10 - INFO - change password for admin
NoneType: None
2021-05-16 10:48:29 - INFO - change password for admin
NoneType: None
2021-05-16 10:48:50 - INFO - edit disount by admin
NoneType: None
2021-05-16 10:49:11 - INFO - creat discount by admin
NoneType: None
2021-05-16 10:49:24 - INFO - edit disount by admin
NoneType: None
2021-05-16 10:49:56 - INFO - edit disount by admin
NoneType: None
2021-05-16 10:50:01 - INFO - admin exit
NoneType: None
2021-05-16 10:56:10 - INFO - edit disount by admin
NoneType: None
2021-05-16 10:56:10 - INFO - edit disount by admin
NoneType: None
2021-05-16 10:56:26 - INFO - edit disount by admin
NoneType: None
2021-05-16 10:56:26 - INFO - edit disount by admin
NoneType: None
2021-05-16 10:56:27 - INFO - admin exit
NoneType: None
2021-05-16 10:56:27 - INFO - admin exit
NoneType: None
2021-05-16 10:57:13 - ERROR - assertion error by costumer, wrong input
Traceback (most recent call last):
  File "D:\Maktab\week_7\final_project\New folder\main_menue.py", line 149, in <module>
    event.Event.display_event('file_event_csv')
  File "D:\Maktab\week_7\final_project\New folder\event.py", line 296, in display_event
    my_logger_event.inf('evnt are displayed sucessfully', exc_info=True)
AttributeError: 'Logger' object has no attribute 'inf'
2021-05-16 10:57:13 - ERROR - assertion error by costumer, wrong input
Traceback (most recent call last):
  File "D:\Maktab\week_7\final_project\New folder\main_menue.py", line 149, in <module>
    event.Event.display_event('file_event_csv')
  File "D:\Maktab\week_7\final_project\New folder\event.py", line 296, in display_event
    my_logger_event.inf('evnt are displayed sucessfully', exc_info=True)
AttributeError: 'Logger' object has no attribute 'inf'
2021-05-16 10:57:13 - ERROR - assertion error by costumer, wrong input
Traceback (most recent call last):
  File "D:\Maktab\week_7\final_project\New folder\main_menue.py", line 149, in <module>
    event.Event.display_event('file_event_csv')
  File "D:\Maktab\week_7\final_project\New folder\event.py", line 296, in display_event
    my_logger_event.inf('evnt are displayed sucessfully', exc_info=True)
AttributeError: 'Logger' object has no attribute 'inf'
2021-05-16 10:58:02 - INFO - but ticket by costumer
NoneType: None
2021-05-16 10:58:02 - INFO - but ticket by costumer
NoneType: None
2021-05-16 10:58:02 - INFO - but ticket by costumer
NoneType: None
2021-05-16 10:59:09 - INFO - but ticket by costumer
NoneType: None
2021-05-16 10:59:09 - INFO - but ticket by costumer
NoneType: None
2021-05-16 10:59:09 - INFO - but ticket by costumer
NoneType: None
2021-05-16 10:59:14 - INFO - costumer exit
NoneType: None
2021-05-16 10:59:14 - INFO - costumer exit
NoneType: None
2021-05-16 10:59:14 - INFO - costumer exit
NoneType: None
2021-05-16 11:18:14 - ERROR - assertion error by costumer, wrong input
Traceback (most recent call last):
  File "D:\Maktab\week_7\final_project\New folder\main_menue.py", line 149, in <module>
    event.Event.display_event('file_event_csv')
  File "D:\Maktab\week_7\final_project\New folder\event.py", line 299, in display_event
    my_logger_event.inf('evnt are displayed sucessfully', exc_info=True)
AttributeError: 'Logger' object has no attribute 'inf'
2021-05-16 11:18:14 - ERROR - assertion error by costumer, wrong input
Traceback (most recent call last):
  File "D:\Maktab\week_7\final_project\New folder\main_menue.py", line 149, in <module>
    event.Event.display_event('file_event_csv')
  File "D:\Maktab\week_7\final_project\New folder\event.py", line 299, in display_event
    my_logger_event.inf('evnt are displayed sucessfully', exc_info=True)
AttributeError: 'Logger' object has no attribute 'inf'
2021-05-16 11:18:14 - ERROR - assertion error by costumer, wrong input
Traceback (most recent call last):
  File "D:\Maktab\week_7\final_project\New folder\main_menue.py", line 149, in <module>
    event.Event.display_event('file_event_csv')
  File "D:\Maktab\week_7\final_project\New folder\event.py", line 299, in display_event
    my_logger_event.inf('evnt are displayed sucessfully', exc_info=True)
AttributeError: 'Logger' object has no attribute 'inf'
2021-05-16 11:18:14 - ERROR - assertion error by costumer, wrong input
Traceback (most recent call last):
  File "D:\Maktab\week_7\final_project\New folder\main_menue.py", line 149, in <module>
    event.Event.display_event('file_event_csv')
  File "D:\Maktab\week_7\final_project\New folder\event.py", line 299, in display_event
    my_logger_event.inf('evnt are displayed sucessfully', exc_info=True)
AttributeError: 'Logger' object has no attribute 'inf'
2021-05-16 11:18:43 - INFO - but ticket by costumer
NoneType: None
2021-05-16 11:18:43 - INFO - but ticket by costumer
NoneType: None
2021-05-16 11:18:43 - INFO - but ticket by costumer
NoneType: None
2021-05-16 11:18:43 - INFO - but ticket by costumer
NoneType: None
2021-05-16 11:18:51 - INFO - costumer exit
NoneType: None
2021-05-16 11:18:51 - INFO - costumer exit
NoneType: None
2021-05-16 11:18:51 - INFO - costumer exit
NoneType: None
2021-05-16 11:18:51 - INFO - costumer exit
NoneType: None
2021-05-16 11:29:02 - ERROR - assertion error by costumer, wrong input
Traceback (most recent call last):
  File "D:\Maktab\week_7\final_project\New folder\main_menue.py", line 149, in <module>
    event.Event.display_event('file_event_csv')
  File "D:\Maktab\week_7\final_project\New folder\event.py", line 301, in display_event
    my_logger_event.inf('evnt are displayed sucessfully', exc_info=True)
AttributeError: 'Logger' object has no attribute 'inf'
2021-05-16 11:29:02 - ERROR - assertion error by costumer, wrong input
Traceback (most recent call last):
  File "D:\Maktab\week_7\final_project\New folder\main_menue.py", line 149, in <module>
    event.Event.display_event('file_event_csv')
  File "D:\Maktab\week_7\final_project\New folder\event.py", line 301, in display_event
    my_logger_event.inf('evnt are displayed sucessfully', exc_info=True)
AttributeError: 'Logger' object has no attribute 'inf'
2021-05-16 11:29:02 - ERROR - assertion error by costumer, wrong input
Traceback (most recent call last):
  File "D:\Maktab\week_7\final_project\New folder\main_menue.py", line 149, in <module>
    event.Event.display_event('file_event_csv')
  File "D:\Maktab\week_7\final_project\New folder\event.py", line 301, in display_event
    my_logger_event.inf('evnt are displayed sucessfully', exc_info=True)
AttributeError: 'Logger' object has no attribute 'inf'
2021-05-16 11:29:02 - ERROR - assertion error by costumer, wrong input
Traceback (most recent call last):
  File "D:\Maktab\week_7\final_project\New folder\main_menue.py", line 149, in <module>
    event.Event.display_event('file_event_csv')
  File "D:\Maktab\week_7\final_project\New folder\event.py", line 301, in display_event
    my_logger_event.inf('evnt are displayed sucessfully', exc_info=True)
AttributeError: 'Logger' object has no attribute 'inf'
2021-05-16 11:29:02 - ERROR - assertion error by costumer, wrong input
Traceback (most recent call last):
  File "D:\Maktab\week_7\final_project\New folder\main_menue.py", line 149, in <module>
    event.Event.display_event('file_event_csv')
  File "D:\Maktab\week_7\final_project\New folder\event.py", line 301, in display_event
    my_logger_event.inf('evnt are displayed sucessfully', exc_info=True)
AttributeError: 'Logger' object has no attribute 'inf'
2021-05-16 11:29:17 - INFO - but ticket by costumer
NoneType: None
2021-05-16 11:29:17 - INFO - but ticket by costumer
NoneType: None
2021-05-16 11:29:17 - INFO - but ticket by costumer
NoneType: None
2021-05-16 11:29:17 - INFO - but ticket by costumer
NoneType: None
2021-05-16 11:29:17 - INFO - but ticket by costumer
NoneType: None
2021-05-16 11:29:34 - INFO - costumer exit
NoneType: None
2021-05-16 11:29:34 - INFO - costumer exit
NoneType: None
2021-05-16 11:29:34 - INFO - costumer exit
NoneType: None
2021-05-16 11:29:34 - INFO - costumer exit
NoneType: None
2021-05-16 11:29:34 - INFO - costumer exit
NoneType: None
2021-05-16 11:31:13 - INFO - but ticket by costumer
NoneType: None
2021-05-16 11:31:13 - INFO - but ticket by costumer
NoneType: None
2021-05-16 11:31:13 - INFO - but ticket by costumer
NoneType: None
2021-05-16 11:31:13 - INFO - but ticket by costumer
NoneType: None
2021-05-16 11:31:13 - INFO - but ticket by costumer
NoneType: None
2021-05-16 11:31:13 - INFO - but ticket by costumer
NoneType: None
2021-05-16 11:31:21 - INFO - costumer exit
NoneType: None
2021-05-16 11:31:21 - INFO - costumer exit
NoneType: None
2021-05-16 11:31:21 - INFO - costumer exit
NoneType: None
2021-05-16 11:31:21 - INFO - costumer exit
NoneType: None
2021-05-16 11:31:21 - INFO - costumer exit
NoneType: None
2021-05-16 11:31:21 - INFO - costumer exit
NoneType: None
2021-05-24 19:21:19 - ERROR - assertion error by costumer, wrong input
Traceback (most recent call last):
  File "D:\Maktab\week_7\final_project\New folder\main_menue.py", line 149, in <module>
    event.Event.display_event('file_event_csv')
  File "D:\Maktab\week_7\final_project\New folder\event.py", line 302, in display_event
    my_logger_event.inf('evnt are displayed sucessfully', exc_info=True)
AttributeError: 'Logger' object has no attribute 'inf'
2021-05-24 19:22:31 - INFO - but ticket by costumer
NoneType: None
2021-05-24 19:22:46 - ERROR - assertion error by costumer, wrong input
Traceback (most recent call last):
  File "D:\Maktab\week_7\final_project\New folder\main_menue.py", line 149, in <module>
    event.Event.display_event('file_event_csv')
  File "D:\Maktab\week_7\final_project\New folder\event.py", line 302, in display_event
    my_logger_event.inf('evnt are displayed sucessfully', exc_info=True)
AttributeError: 'Logger' object has no attribute 'inf'
2021-05-24 19:24:57 - INFO - costumer exit
NoneType: None
2021-05-24 19:29:32 - ERROR - assertion error by costumer, wrong input
Traceback (most recent call last):
  File "D:\Maktab\week_7\final_project\New folder\main_menue.py", line 149, in <module>
    event.Event.display_event('file_event_csv')
  File "D:\Maktab\week_7\final_project\New folder\event.py", line 302, in display_event
    my_logger_event.inf('evnt are displayed sucessfully', exc_info=True)
AttributeError: 'Logger' object has no attribute 'inf'
2021-05-24 19:29:32 - ERROR - assertion error by costumer, wrong input
Traceback (most recent call last):
  File "D:\Maktab\week_7\final_project\New folder\main_menue.py", line 149, in <module>
    event.Event.display_event('file_event_csv')
  File "D:\Maktab\week_7\final_project\New folder\event.py", line 302, in display_event
    my_logger_event.inf('evnt are displayed sucessfully', exc_info=True)
AttributeError: 'Logger' object has no attribute 'inf'
2021-05-24 19:30:30 - INFO - but ticket by costumer
NoneType: None
2021-05-24 19:30:30 - INFO - but ticket by costumer
NoneType: None
2021-05-24 19:30:40 - ERROR - assertion error by costumer, wrong input
Traceback (most recent call last):
  File "D:\Maktab\week_7\final_project\New folder\main_menue.py", line 147, in <module>
    num=int(input('what do you want to do: \n 1. See current Event\n 2. Buy ticket\n 3. Exit\n '))
  File "C:\Users\1234\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 863, in raw_input
    password=False,
  File "C:\Users\1234\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 904, in _input_request
    raise KeyboardInterrupt("Interrupted by user") from None
KeyboardInterrupt: Interrupted by user
2021-05-24 19:30:40 - ERROR - assertion error by costumer, wrong input
Traceback (most recent call last):
  File "D:\Maktab\week_7\final_project\New folder\main_menue.py", line 147, in <module>
    num=int(input('what do you want to do: \n 1. See current Event\n 2. Buy ticket\n 3. Exit\n '))
  File "C:\Users\1234\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 863, in raw_input
    password=False,
  File "C:\Users\1234\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 904, in _input_request
    raise KeyboardInterrupt("Interrupted by user") from None
KeyboardInterrupt: Interrupted by user
2021-05-24 19:32:10 - ERROR - assertion error by costumer, wrong input
Traceback (most recent call last):
  File "D:\Maktab\week_7\final_project\New folder\main_menue.py", line 147, in <module>
    num=int(input('what do you want to do: \n 1. See current Event\n 2. Buy ticket\n 3. Exit\n '))
ValueError: invalid literal for int() with base 10: ''
2021-05-24 19:32:10 - ERROR - assertion error by costumer, wrong input
Traceback (most recent call last):
  File "D:\Maktab\week_7\final_project\New folder\main_menue.py", line 147, in <module>
    num=int(input('what do you want to do: \n 1. See current Event\n 2. Buy ticket\n 3. Exit\n '))
ValueError: invalid literal for int() with base 10: ''
2021-05-24 19:32:10 - ERROR - assertion error by costumer, wrong input
Traceback (most recent call last):
  File "D:\Maktab\week_7\final_project\New folder\main_menue.py", line 147, in <module>
    num=int(input('what do you want to do: \n 1. See current Event\n 2. Buy ticket\n 3. Exit\n '))
ValueError: invalid literal for int() with base 10: ''
2021-05-24 19:32:10 - ERROR - assertion error by costumer, wrong input
Traceback (most recent call last):
  File "D:\Maktab\week_7\final_project\New folder\main_menue.py", line 147, in <module>
    num=int(input('what do you want to do: \n 1. See current Event\n 2. Buy ticket\n 3. Exit\n '))
ValueError: invalid literal for int() with base 10: ''
2021-05-24 19:34:19 - ERROR - assertion error by costumer, wrong input
Traceback (most recent call last):
  File "D:\Maktab\week_7\final_project\New folder\main_menue.py", line 147, in <module>
    num=int(input('what do you want to do: \n 1. See current Event\n 2. Buy ticket\n 3. Exit\n '))
  File "C:\Users\1234\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 863, in raw_input
    password=False,
  File "C:\Users\1234\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 904, in _input_request
    raise KeyboardInterrupt("Interrupted by user") from None
KeyboardInterrupt: Interrupted by user
2021-05-24 19:34:19 - ERROR - assertion error by costumer, wrong input
Traceback (most recent call last):
  File "D:\Maktab\week_7\final_project\New folder\main_menue.py", line 147, in <module>
    num=int(input('what do you want to do: \n 1. See current Event\n 2. Buy ticket\n 3. Exit\n '))
  File "C:\Users\1234\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 863, in raw_input
    password=False,
  File "C:\Users\1234\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 904, in _input_request
    raise KeyboardInterrupt("Interrupted by user") from None
KeyboardInterrupt: Interrupted by user
2021-05-24 19:34:31 - ERROR - assertion error by costumer, wrong input
Traceback (most recent call last):
  File "D:\Maktab\week_7\final_project\New folder\main_menue.py", line 147, in <module>
    num=int(input('what do you want to do: \n 1. See current Event\n 2. Buy ticket\n 3. Exit\n '))
  File "C:\Users\1234\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 863, in raw_input
    password=False,
  File "C:\Users\1234\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 904, in _input_request
    raise KeyboardInterrupt("Interrupted by user") from None
KeyboardInterrupt: Interrupted by user
2021-05-24 19:34:31 - ERROR - assertion error by costumer, wrong input
Traceback (most recent call last):
  File "D:\Maktab\week_7\final_project\New folder\main_menue.py", line 147, in <module>
    num=int(input('what do you want to do: \n 1. See current Event\n 2. Buy ticket\n 3. Exit\n '))
  File "C:\Users\1234\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 863, in raw_input
    password=False,
  File "C:\Users\1234\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 904, in _input_request
    raise KeyboardInterrupt("Interrupted by user") from None
KeyboardInterrupt: Interrupted by user
2021-05-24 19:34:35 - ERROR - assertion error by costumer, wrong input
Traceback (most recent call last):
  File "D:\Maktab\week_7\final_project\New folder\main_menue.py", line 147, in <module>
    num=int(input('what do you want to do: \n 1. See current Event\n 2. Buy ticket\n 3. Exit\n '))
  File "C:\Users\1234\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 863, in raw_input
    password=False,
  File "C:\Users\1234\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 904, in _input_request
    raise KeyboardInterrupt("Interrupted by user") from None
KeyboardInterrupt: Interrupted by user
2021-05-24 19:34:35 - ERROR - assertion error by costumer, wrong input
Traceback (most recent call last):
  File "D:\Maktab\week_7\final_project\New folder\main_menue.py", line 147, in <module>
    num=int(input('what do you want to do: \n 1. See current Event\n 2. Buy ticket\n 3. Exit\n '))
  File "C:\Users\1234\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 863, in raw_input
    password=False,
  File "C:\Users\1234\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 904, in _input_request
    raise KeyboardInterrupt("Interrupted by user") from None
KeyboardInterrupt: Interrupted by user
2021-05-24 19:36:28 - ERROR - assertion error by costumer, wrong input
Traceback (most recent call last):
  File "D:\Maktab\week_7\final_project\New folder\main_menue.py", line 149, in <module>
    event.Event.display_event('file_event_csv')
  File "D:\Maktab\week_7\final_project\New folder\event.py", line 302, in display_event
    my_logger_event.inf('evnt are displayed sucessfully', exc_info=True)
AttributeError: 'Logger' object has no attribute 'inf'
2021-05-24 19:36:39 - INFO - costumer exit
NoneType: None
2021-05-24 20:11:52 - ERROR - assertion error by costumer, wrong input
Traceback (most recent call last):
  File "D:\Maktab\week_7\final_project\New folder\main_menue.py", line 149, in <module>
    event.Event.display_event('file_event_csv')
  File "D:\Maktab\week_7\final_project\New folder\event.py", line 302, in display_event
    my_logger_event.inf('evnt are displayed sucessfully', exc_info=True)
AttributeError: 'Logger' object has no attribute 'inf'
2021-05-24 20:15:51 - INFO - but ticket by costumer
NoneType: None
2021-05-24 20:18:03 - ERROR - assertion error by costumer, wrong input
Traceback (most recent call last):
  File "D:\Maktab\week_7\final_project\New folder\main_menue.py", line 147, in <module>
    num=int(input('what do you want to do: \n 1. See current Event\n 2. Buy ticket\n 3. Exit\n '))
ValueError: invalid literal for int() with base 10: ''
2021-05-24 20:18:03 - ERROR - assertion error by costumer, wrong input
Traceback (most recent call last):
  File "D:\Maktab\week_7\final_project\New folder\main_menue.py", line 147, in <module>
    num=int(input('what do you want to do: \n 1. See current Event\n 2. Buy ticket\n 3. Exit\n '))
ValueError: invalid literal for int() with base 10: ''
2021-05-24 20:18:03 - ERROR - assertion error by costumer, wrong input
Traceback (most recent call last):
  File "D:\Maktab\week_7\final_project\New folder\main_menue.py", line 147, in <module>
    num=int(input('what do you want to do: \n 1. See current Event\n 2. Buy ticket\n 3. Exit\n '))
ValueError: invalid literal for int() with base 10: ''
2021-05-24 20:18:04 - ERROR - assertion error by costumer, wrong input
Traceback (most recent call last):
  File "D:\Maktab\week_7\final_project\New folder\main_menue.py", line 147, in <module>
    num=int(input('what do you want to do: \n 1. See current Event\n 2. Buy ticket\n 3. Exit\n '))
ValueError: invalid literal for int() with base 10: ''
2021-05-24 20:18:04 - ERROR - assertion error by costumer, wrong input
Traceback (most recent call last):
  File "D:\Maktab\week_7\final_project\New folder\main_menue.py", line 147, in <module>
    num=int(input('what do you want to do: \n 1. See current Event\n 2. Buy ticket\n 3. Exit\n '))
ValueError: invalid literal for int() with base 10: ''
2021-05-24 20:18:04 - ERROR - assertion error by costumer, wrong input
Traceback (most recent call last):
  File "D:\Maktab\week_7\final_project\New folder\main_menue.py", line 147, in <module>
    num=int(input('what do you want to do: \n 1. See current Event\n 2. Buy ticket\n 3. Exit\n '))
ValueError: invalid literal for int() with base 10: ''
2021-05-24 20:18:19 - ERROR - assertion error by costumer, wrong input
Traceback (most recent call last):
  File "D:\Maktab\week_7\final_project\New folder\main_menue.py", line 147, in <module>
    num=int(input('what do you want to do: \n 1. See current Event\n 2. Buy ticket\n 3. Exit\n '))
  File "C:\Users\1234\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 863, in raw_input
    password=False,
  File "C:\Users\1234\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 904, in _input_request
    raise KeyboardInterrupt("Interrupted by user") from None
KeyboardInterrupt: Interrupted by user
2021-05-24 20:19:55 - INFO - but ticket by costumer
NoneType: None
2021-05-24 20:20:01 - ERROR - assertion error by costumer, wrong input
Traceback (most recent call last):
  File "D:\Maktab\week_7\final_project\New folder\main_menue.py", line 149, in <module>
    event.Event.display_event('file_event_csv')
  File "D:\Maktab\week_7\final_project\New folder\event.py", line 302, in display_event
    my_logger_event.inf('evnt are displayed sucessfully', exc_info=True)
AttributeError: 'Logger' object has no attribute 'inf'
2021-05-24 20:31:42 - ERROR - assertion error by costumer, wrong input
Traceback (most recent call last):
  File "D:\Maktab\week_7\final_project\New folder\main_menue.py", line 147, in <module>
    num=int(input('what do you want to do: \n 1. See current Event\n 2. Buy ticket\n 3. Exit\n '))
  File "C:\Users\1234\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 863, in raw_input
    password=False,
  File "C:\Users\1234\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 904, in _input_request
    raise KeyboardInterrupt("Interrupted by user") from None
KeyboardInterrupt: Interrupted by user
2021-05-24 20:31:54 - ERROR - assertion error by costumer, wrong input
Traceback (most recent call last):
  File "D:\Maktab\week_7\final_project\New folder\main_menue.py", line 147, in <module>
    num=int(input('what do you want to do: \n 1. See current Event\n 2. Buy ticket\n 3. Exit\n '))
  File "C:\Users\1234\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 863, in raw_input
    password=False,
  File "C:\Users\1234\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 904, in _input_request
    raise KeyboardInterrupt("Interrupted by user") from None
KeyboardInterrupt: Interrupted by user
2021-05-24 20:32:32 - ERROR - assertion error by costumer, wrong input
Traceback (most recent call last):
  File "D:\Maktab\week_7\final_project\New folder\main_menue.py", line 149, in <module>
    event.Event.display_event('file_event_csv')
  File "D:\Maktab\week_7\final_project\New folder\event.py", line 305, in display_event
    my_logger_event.inf('evnt are displayed sucessfully', exc_info=True)
AttributeError: 'Logger' object has no attribute 'inf'
2021-05-24 20:32:47 - INFO - but ticket by costumer
NoneType: None
2021-05-24 20:32:54 - ERROR - assertion error by costumer, wrong input
Traceback (most recent call last):
  File "D:\Maktab\week_7\final_project\New folder\main_menue.py", line 149, in <module>
    event.Event.display_event('file_event_csv')
  File "D:\Maktab\week_7\final_project\New folder\event.py", line 305, in display_event
    my_logger_event.inf('evnt are displayed sucessfully', exc_info=True)
AttributeError: 'Logger' object has no attribute 'inf'
2021-05-24 20:38:22 - ERROR - assertion error by costumer, wrong input
Traceback (most recent call last):
  File "D:\Maktab\week_7\final_project\New folder\main_menue.py", line 147, in <module>
    num=int(input('what do you want to do: \n 1. See current Event\n 2. Buy ticket\n 3. Exit\n '))
  File "C:\Users\1234\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 863, in raw_input
    password=False,
  File "C:\Users\1234\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 904, in _input_request
    raise KeyboardInterrupt("Interrupted by user") from None
KeyboardInterrupt: Interrupted by user
